### ISSUE TITLE
More insight into what kubed-sh is pulling / doing during setup.

### ISSUE THREAD

**Issue by plombardi89** [mhausenblas/kubed-sh#10]
Interesting tool... One thing that worried me slightly as the program was starting was this message:

```text
Pre-pulling images, this may take up to 30 seconds to complete, please stand by.
Don't worry, this is a one-time only operation ;)
```

While I'm sure kubed-sh has to do some background Kubernetes work it would be nice to tell the user what images are being pulled and where they are going.

**Comment by mhausenblas** [comment]
Agreed! See also #11
