### ISSUE TITLE
Recreating default global environment

### ISSUE THREAD

**Issue by gtq** [mhausenblas/kubed-sh#23]
## Environment

- [ ] Linux
- [x] macOS

## Versions

- Kubernetes (hint: `kubectl version --short`): 
Client Version: v1.14.1
Server Version: v1.14.1
- `kubed-sh`: 0.5.1

## Problem or feature request?

Problem/issue request. 
Somewhat related to: https://github.com/mhausenblas/kubed-sh/issues/10

## Details

When I cleared my minikube, I would get a prompt like below:
[minikube::defaultpod "ns" deleted]$

How do I recreate the default environment? 
What are the details for it?

**Comment by mhausenblas** [comment]
Thanks @gtq and can you let me know what `kubectl config get-contexts` gives you?

**Comment by gtq** [comment]
I ran:
$ kubectl config get-contexts
and I get:
CURRENT  NAME        CLUSTER  AUTHINFO  NAMESPACE
*                 minikube    minikube   minikube

**Comment by mhausenblas** [comment]
OK, thanks @gtq I see. So, apparently the namespace is not set in the context. Let's bring it back (might want to check with `kubectl get ns` if the `default` namespace is still there, if not, create it with `kubectl create ns default`. After this, do:

```sh
$ kubectl config set-context $(kubectl config current-context) --namespace=default
```

**Comment by gtq** [comment]
okay, I now get:
| CURRENT | NAME | CLUSTER | AUTHINFO | NAMESPACE |
| * | minikube | minikube | minikube | default |

I'm still getting the line below. Anything else I should recreate?
[minikube::defaultpod "ns" deleted]$

**Comment by mhausenblas** [comment]
Ha! Only now figured what the error actually says (due to formatting). Apparently, in addition to the expected namespace (`default`) the `kubectl` command in [line 152](https://github.com/mhausenblas/kubed-sh/blob/f19b687c389d5a8409d78ed6206572f21376188d/envs.go#L152) also returns the result `pod "ns" deleted` which together gives `defaultpod "ns" deleted`. Now, this might be due to the `kubectl` version you're using. Let's check that. Can you tell me what the following output is, please:

```sh
$ kubectl version --short
```

**Comment by gtq** [comment]
I have:
Client Version: v1.14.1
Server Version: v1.14.0
I didn't set the KUBECTL_BINARY variable.

**Comment by mhausenblas** [comment]
Thanks a lot @gtq! So it very likely is the `kubectl` version. Will do some testing and also add a prerequisites section to make it clear ;)

**Comment by ealebed** [comment]
@mhausenblas 
Do you have any updates?

**Comment by mhausenblas** [comment]
Yup, I think I figured what is is but no cycles yet to fix it

**Comment by mhausenblas** [comment]
Since v0.6 now fixed.
